define(function(){
  var COMPLAINTS = [
              ' Head Ache '															,
              ' Vertigo '																,
              ' Neck Pain '															,
              ' Neck Stiffness '												,
              ' Radiculopathy Left Upper Limb '					,
              ' Radiculopathy Right Upper Limb '				,
              ' Radiculopathy Both Upper Limbs '				,
              ' Tingling Right Upper Limb '							,
              ' Tingling Left Upper Limb '							,
              ' Numbness and Weakness Right Upper Limb ',
              ' Numbness and Weakness Left Upper Limb '	,
              ' Numbness and Weakness Both Upper Limb '	,
              ' Clumsiness of Left Hand '								,
              ' Clumsiness of Right Hand '							,
              ' Clumsiness of Both Hands '							,
              ' Unsteady Gait '													,
              ' Chest Pain'															,
              ' Shoulder Girdle and Periscapular pain '	,
              ' Shoulder Pain '													,
              ' Shoulder Stiffness '										,
              '	Arm Pain'																,
              ' Elbow Pain '														,
              '	Forearm Pain'														,
              '	Wrist Pain'															,
              '	Hand Pain'															,
              ' Abdominal Pain'													,
              ' Inguinal Area Pain'											,
              ' Flank Pain'															,
              ' Periumblical Pain'											,
              ' Dorsal Back Pain'												,
              ' Thoracolumbar Back Pain'								,
              ' Low Back Pain'													,
              '	Coccygodynia'														,
              ' Sciatica Left'													,
              ' Sciatica Right'													,
              ' Sciatica Bilateral'											,
              ' Sciatica & Weakness Left'								,
              ' Sciatica & Weakness Right'							,
              ' Sciatica & Weakness Bilateral'					,
              ' Hip Pain Right'													,
              ' Hip Pain Left'													,
              ' Hip Pain Bilateral'											,
              ' Thigh Pain Right'												,
              ' Thigh Pain Left'												,
              ' Thigh Pain Bilateral'										,
              ' Knee Pain Left'													,
              ' Knee Pain Right'												,
              ' Knee Pain Bilateral'										,
              ' Knee Instability Left'									,
              ' Knee Instability Right'									,
              ' Knee Instability Bilateral'							,
              ' Knee Swelling Right'										,
              ' Knee Swelling Left'											,
              ' Knee Swelling Bilateral'								,
              ' Leg Swelling Right'											,
              ' Leg Swelling Left'											,
              ' Leg Swelling Bilateral'									,
              ' Leg Pain Right'													,
              ' Leg Pain Left'													,
              ' Leg Pain Bilateral'											,
              ' Ankle Pain Left'												,
              ' Ankle Pain Right'												,
              ' Ankle Pain Bilateral'										,
              ' Foot Pain Bilateral'										,
              ' Foot Pain Right'												,
              ' Foot Pain Left'													,
  ];
  return COMPLAINTS;
});